name: github-merged-pr
description: Merges the target branch from the repo and errors in case of conflicts
author: https://github.com/gugahoi
requirements: []
configuration:
  properties: {}
  required: []
